### ISSUE TITLE
Uploading PDFs on GDPR Settings don't work

### ISSUE THREAD

**Issue by cuatrocento** [veda-consulting/uk.co.vedaconsulting.gdpr#101]
GDPR 2.5
CiviCrRM 4.7.4
Drupal 7.55

When I upload Default Terms and Conditions and Data Policy file on GDPR settings page nothing occur.

![gdpr-settings](https://user-images.githubusercontent.com/39189451/40167700-f9dddf20-59c1-11e8-8aa9-2a7414f75237.png)

**Comment by rsbroughton** [comment]
We had the same problem with a Civi 4.6 site. Our hosting company (Circle) identified it as not an upload problem, but rather Civi not finding the uploaded file, and reported the fix that they applied as: 
This has to do with a bug /issue in civicrm that uses a variable to automatically set the site root and the setup on the server that uses symbolic links. The two are not mutually compatible, so I've changed Civi's config to accommodate (using a longer form that doesn;t use the symlinks.)

**Comment by veda-consulting** [comment]
@rsbroughton thanks for the info
@cuatrocento please try the suggestion and feedback, we dont plan to make any changes to the extension to override core functions

**Comment by cuatrocento** [comment]
I'm sorry but I do not know what you mean. If you could be a little more concrete, I would appreciate it. URL Resourses Settings? Thks
