### ISSUE TITLE
Uninstall leaves custom data and activities

### ISSUE THREAD

**Issue by mikantchap** [veda-consulting/uk.co.vedaconsulting.gdpr#102]
We have uninstalled ver 2.5 but it has left entries behind.

Datasets are:

·        Data Policy Acceptance
·        Event terms and conditions
·        Event terms and conditions acceptance
·        Contribution Page terms and conditions
·        Contribution terms and conditions acceptance 

Activities:
·        Data Policy Acceptance (140)
·        Update Communication Preferences (141)
·        Event Terms and Conditions Acceptance (142)
·        Contribution Terms and Conditions Acceptance (143)
·        GDPR Forget me (144)

1) Is this correct behaviour?
2) Is there anything to stop us manually deleting them?

The reason its an issue for our customer is that they are running into the MySQL issue of too many joins:

https://dev.mysql.com/doc/refman/8.0/en/joins-limits.html

Thanks Mike

**Comment by veda-consulting** [comment]
@mikantchap yes, this is. We need to keep all the history in place for anyone who may have accepted the Data policies or terms and conditions etc. If you haven't been using them then your free to delete.

Out of curiosity what was the query being produced and how was the gdpr extension adding to it? If we know then we can look at potentially patching the issue.

**Comment by mikantchap** [comment]
I've supplied the backtrace below if its any use. I think this problem crops up when there are too many custom data sets and/or activities regardless of whether the gdpr module is present.

Thanks Mike

$backTrace = #
0 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/CRM/Core/Error.php(914): CRM_Core_Error::backtrace("backTrace", TRUE) #
1 [internal function](): CRM_Core_Error::exceptionHandler(Object(DB_Error)) #
2 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/packages/PEAR.php(931): call_user_func((Array:2), Object(DB_Error)) #
3 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/packages/DB.php(976): PEAR_Error->PEAR_Error("DB Error: unknown error", -1, 16, (Array:2), "SELECT a.source_record_id as `source_record_id`, a.activity_type_id as `activ...") #
4 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/packages/PEAR.php(564): DB_Error->DB_Error(-1, 16, (Array:2), "SELECT a.source_record_id as `source_record_id`, a.activity_type_id as `activ...") #
5 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/packages/DB/common.php(1905): PEAR->raiseError(NULL, -1, NULL, NULL, "SELECT a.source_record_id as `source_record_id`, a.activity_type_id as `activ...", "DB_Error", TRUE) #
6 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/packages/DB/mysql.php(895): DB_common->raiseError(-1, NULL, NULL, NULL, "1116 ** Too many tables; MySQL can only use 61 tables in a join") #
7 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/packages/DB/mysql.php(328): DB_mysql->mysqlRaiseError() #
8 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/packages/DB/common.php(1216): DB_mysql->simpleQuery("SELECT a.source_record_id as `source_record_id`, a.activity_type_id as `activ...") #
9 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/packages/DB/DataObject.php(2442): DB_common->query("SELECT a.source_record_id as `source_record_id`, a.activity_type_id as `activ...") #
10 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/packages/DB/DataObject.php(1634): DB_DataObject->_query("SELECT a.source_record_id as `source_record_id`, a.activity_type_id as `activ...") #
11 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/CRM/Core/DAO.php(321): DB_DataObject->query("SELECT a.source_record_id as `source_record_id`, a.activity_type_id as `activ...") #
12 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/CRM/Core/DAO.php(1181): CRM_Core_DAO->query("SELECT a.source_record_id as `source_record_id`, a.activity_type_id as `activ...", TRUE) #
13 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/Civi/API/SelectQuery.php(290): CRM_Core_DAO::executeQuery("SELECT a.source_record_id as `source_record_id`, a.activity_type_id as `activ...") #
14 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/api/v3/utils.php(1359): Civi\API\SelectQuery->run() #
15 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/api/v3/Activity.php(267): _civicrm_api3_basic_get("CRM_Activity_BAO_Activity", (Array:5), FALSE, "Activity", Object(CRM_Utils_SQL_Select)) #
16 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_activity_get((Array:5)) #
17 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/Civi/API/Kernel.php(96): Civi\API\Provider\MagicFunctionProvider->invoke((Array:9)) #
18 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/api/api.php(23): Civi\API\Kernel->run("Activity", "get", (Array:5), NULL) #
19 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/api/api.php(43): civicrm_api("Activity", "get", (Array:5)) #
20 /home/XXXXXXXX/public_html/sites/default/files/civicrm/extensions/uk.co.vedaconsulting.gdpr-master/CRM/Gdpr/SLA/Utils.php(119): civicrm_api3("Activity", "get", (Array:4)) #
21 /home/XXXXXXXX/public_html/sites/default/files/civicrm/extensions/uk.co.vedaconsulting.gdpr-master/gdpr.php(522): CRM_Gdpr_SLA_Utils::getContactLastAcceptance("8304") #
22 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/CRM/Utils/Hook.php(201): gdpr_civicrm_pageRun(Object(CRM_Contact_Page_View_Summary)) #
23 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/CRM/Utils/Hook/DrupalBase.php(87): CRM_Utils_Hook->runHooks((Array:134), "civicrm_pageRun", 1, Object(CRM_Contact_Page_View_Summary), NULL, NULL, NULL, NULL, NULL) #
24 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/CRM/Utils/Hook.php(736): CRM_Utils_Hook_DrupalBase->invoke(1, Object(CRM_Contact_Page_View_Summary), NULL, NULL, NULL, NULL, NULL, "civicrm_pageRun") #
25 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/CRM/Core/Page.php(182): CRM_Utils_Hook::pageRun(Object(CRM_Contact_Page_View_Summary)) #
26 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/CRM/Contact/Page/View/Summary.php(103): CRM_Core_Page->run() #
27 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(312): CRM_Contact_Page_View_Summary->run((Array:3), NULL) #
28 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:14)) #
29 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:3)) #
30 /home/XXXXXXXX/public_html/sites/all/modules/civicrm/drupal/civicrm.module(482): CRM_Core_Invoke::invoke((Array:3)) #
31 [internal function](): civicrm_invoke("contact", "view") #
32 /home/XXXXXXXX/public_html/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2)) #
33 /home/XXXXXXXX/public_html/index.php(21): menu_execute_active_handler() #
34 {main}

**Comment by mikantchap** [comment]
Just for reference, this is the too many table issue:

https://issues.civicrm.org/jira/browse/CRM-21491

https://civicrm.stackexchange.com/questions/20890/too-many-tables-mysql-limitation-civicrm-api-errors

**Comment by veda-consulting** [comment]
@mikantchap thanks for this. As you've highlighted this is a MySQL limit coupled with how CiviCRM custom data is stored. You could disable old unused custom field sets to try and bring your joins back down. Closing for now as this isn't an issue introduced by the extension as such.
