### ISSUE TITLE
Extra div tags on event and contribution pages

### ISSUE THREAD

**Issue by mhawksey** [veda-consulting/uk.co.vedaconsulting.gdpr#104]
On Event and Contribution pages we encountered an issue with two extra closing <div> tags which caused a problem in our website:

![image](https://user-images.githubusercontent.com/204892/40297407-a90952c8-5cd7-11e8-89cc-21e3d214ab16.png)

Commenting out [lines 41-42 in TermsConditionsField.tpl](https://github.com/veda-consulting/uk.co.vedaconsulting.gdpr/blob/e4fcc47c3a2ab6ff6eff2f9efca7e2d3ad5daeb2/templates/CRM/Gdpr/TermsConditionsField.tpl#L41-L42) fixed the issue for us.

Is this a bug? With the GDPR extension disabled the page renders ok so the extension appears to be the only difference. An example event page we were having problems with is here https://www.alt.ac.uk/civicrm/event/register?id=360&reset=1

**Comment by veda-consulting** [comment]
@mhawksey we'll take a look

**Comment by eileenmcnaughton** [comment]
There is a commit against this - closable?

**Comment by veda-consulting** [comment]
@eileenmcnaughton yeah, we'll close once we do the release on Friday
