### ISSUE TITLE
Add activity for "Forget Me"

### ISSUE THREAD

**Issue by mattwire** [veda-consulting/uk.co.vedaconsulting.gdpr#11]
It would be useful if an activity could be recorded on the "forgotten" contact record to record when it was anonymised.  Otherwise it's not easy to see when it was anonymised - could also be useful to record a reason.

**Comment by tttp** [comment]
isn't it the last modified date for the contact?

**Comment by mattwire** [comment]
@tttp It could be, but what if you later modify the anonymous contact for some reason (eg. a bulk update, a tag etc).  Then you lose the date that the contact was anonymised.

**Comment by veda-consulting** [comment]
@mattwire @tttp yeah I think an activity would be useful anyway to see who did it etc.

**Comment by veda-consulting** [comment]
@mathavanveda @tttp this has been done and will in the latest release due out today or tomorrow. Keep an eye out - theres also the addition of emailing the designated DPO with the contact ID for a belt and braces approach.
