### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by sluc23** [veda-consulting/uk.co.vedaconsulting.gdpr#110]
There are some remaining ts() instead of E::ts() calls.
PR soon..

**Comment by veda-consulting** [comment]
@sluc23 thanks

**Comment by alejandro-ixiam** [comment]
Hi @veda-consulting , is there any chance to release version 2.6 of the extension in the upcoming days? Thank you very much!!!

**Comment by veda-consulting** [comment]
@alejandro-ixiam we're planning on it tomorrow as we have a bunch of other minor things to go into it.

**Comment by alejandro-ixiam** [comment]
@veda-consulting great and thanks for the great work!!
