### ISSUE TITLE
Currently 'forget contact' permission in contact GDPR tab requires 'administer GDPR' permission

### ISSUE THREAD

**Issue by mhawksey** [veda-consulting/uk.co.vedaconsulting.gdpr#114]
Currently to use the 'forget contact' button the user also needs 'administer GDPR' permission. It would be good if this the admin permission was not required to allow delegation to team members.

Relevant lines: 
https://github.com/veda-consulting/uk.co.vedaconsulting.gdpr/blob/fe3e51145abc8822dd1e447e5b16122e9ecaac17/templates/CRM/Gdpr/Page/Tab.tpl#L2-L10

**Comment by tbuytaer** [comment]
Instead of removing the permission check it would seem better to replace it with a separate permission to "forget contact".
Otherwise anyone with some kind of access to CiviCRM can forget contacts.

See PR #19
