### ISSUE TITLE
Privacy Policy PDF Link

### ISSUE THREAD

**Issue by troeim** [veda-consulting/uk.co.vedaconsulting.gdpr#119]
Hello all
Thank you very much for this valuable extension. 

I am running this on Wordpress 4.9.6 and Civicrm 4.7.14

When I upload a new Privacy Policy, then even when I click on the linked document just below the link is distorted and the document not found. 

Example:
Linked to: example.com/wp-admin/wp-content/plugins/files/civicrm/persist/contribute/PrivacyPolicy.pdf
Correct Link: example.com/wp-content/plugins/files/civicrm/persist/contribute/PrivacyPolicy.pdf
Link embedded in the website: example.com/civicrm/wp-content/plugins/files/civicrm/persist/contribute/PrivacyPolicy.pdf

Any idea why there is either wp-admin or civicrm in front of the correct path? Could it be related to where I store the extension? My current directory is wp-content/civicrm/custom_ext.

Thanks for your help!
troeim

**Comment by veda-consulting** [comment]
@troeim what version of the extension are you using? I believe this issue has been resolved in the latest version.

**Comment by veda-consulting** [comment]
Closing - please re-open if you're still having issues.
