### ISSUE TITLE
Anon overwriting current user

### ISSUE THREAD

**Issue by Leftspace21** [veda-consulting/uk.co.vedaconsulting.gdpr#121]
I am using the GDPR extension as a sign up page to recieve newsletter. This is designed for public users.

https://www.marx-memorial-library.org/index.php?option=com_civicrm&task=civicrm/gdpr/comms-prefs/update

They then click MML newsletter and accept data policy - if the email is on the system then members first name and last name can be overwritten. The profile being used has Allow duplicate contact to be created however when opening borwser in private window and changing name with same email address results in original entry being overwritten and no duplicate created.

Joomla 3.8.8 and civi 5.1

**Comment by veda-consulting** [comment]
@Leftspace21 thanks for reporting this, we'll add to the next release 2.7
