### ISSUE TITLE
Privacy Policy using URL

### ISSUE THREAD

**Issue by robbrandt** [veda-consulting/uk.co.vedaconsulting.gdpr#125]
Feature request...

I would prefer the privacy policy to be a link to a URL rather than an upload.  Linking to a page would reduce privacy policy maintenance to just one true source.

**Comment by veda-consulting** [comment]
@robbrandt this should have been available in the last release? Please confirm if its not.

**Comment by veda-consulting** [comment]
closing for now, it should be in the last release

**Comment by robbrandt** [comment]
Sorry for the delay.

I installed v2.6.  I have confirmed it is 2.6.  Here is a screen shot of the "Terms & Conditions: Events and Contribution Pages" section of configuration.

![Screenshot ](https://screenshotscdn.firefoxusercontent.com/images/23c6e085-1abc-45eb-a2e3-cf645db10af4.png)

Am I missing something?

**Comment by freeform-sg** [comment]
@veda-consulting  Actually, this is not fully complete. While you can select URLs for Privacy Policy and Terms & Conditions on the main GDPR page, you are still limited to a pdf on the individual contribution Terms & Conditions tabs.
