### ISSUE TITLE
Allow "Forget Me" to optionally delete some activity types

### ISSUE THREAD

**Issue by mattwire** [veda-consulting/uk.co.vedaconsulting.gdpr#13]
Some activity types (eg. Inbound email) allow you to easily identify the contact after it has been anonymised.  We should add an option to delete certain activity types when executing "Forget Me".

**Comment by veda-consulting** [comment]
@mattwire yes, seems like a good idea. We'll add it to our queue.

**Comment by veda-consulting** [comment]
Released into v2.6
