### ISSUE TITLE
No menu entry

### ISSUE THREAD

**Issue by AlphaDE** [veda-consulting/uk.co.vedaconsulting.gdpr#130]
Having just installed/activated the extension into my civiCRM 5.1.2 on Wordpress installation, I do not see the menu entry in the contacts section. I'm WP admin.

The webserver error log shows

[Wed Jun 06 23:41:51.801162 2018] [:error] [pid 12384] [client 74.110.114.217:55427] FastCGI: server "/var/www/clients/clientx/w
eb7/cgi-bin/php5-fcgi-*-443-mysite" stderr: PHP message: PHP Warning:  array_keys() expects parameter 1 to be
array, null given in /var/www/clients/clientx/weby/web/wp-content/uploads/civicrm/ext/uk.co.vedaconsulting.gdpr-2.6/gdpr.php on
line 417

and a strack trace.

How to fix, what am I doing wrong?`

PHP Version: | 7.1.13
WordPress Version: | 4.9.6
Server Software: | Apache/2.4.33 (Debian)

**Comment by AlphaDE** [comment]
Later... after doing some debugging, I found that line 413 in gdpr.php

$contactsMenuId = CRM_Core_DAO::getFieldValue('CRM_Core_BAO_Navigation', 'Contacts', 'id', 'name');

returns the navID element. Afterwards, that value (in my case 15) is used to access the Contacts array item by index. But this index in my case is two and not 15 so the access attempt fails.

Walking and checking the $params array manually works:

  $contactsMenuId = 0;
  $menu_ctr=0;
  foreach ($params as $param)
  {
    if (!strcmp($param['attributes']['name'], 'Contacts'))
    {
      $contactsMenuId = $menu_ctr;
      break;
    }
    $menu_ctr++;
  }

**Comment by veda-consulting** [comment]
@AlphaDE thanks for that, any chance of a patch if you've made a fix/amendment?

**Comment by AlphaDE** [comment]
I'll look, I simply replaced line 413 with the code given above and it solved my problem.

**Comment by AlphaDE** [comment]
Done, see pull request.

**Comment by TerryVeda** [comment]
Resolved - menu now appearing
