### ISSUE TITLE
Communication Preferences with Newsletter Sign-Up - option to change user / sign up as new user?

### ISSUE THREAD

**Issue by jimhoward295** [veda-consulting/uk.co.vedaconsulting.gdpr#144]
Hi, 

We are using the Communication Preferences as the default for existing users to edit their details, opt-out and accept the new policy agreements. As well, we want to use it for new users signing up to the newsletter, so that they have to agree to the policy when signing up. 

This works fine if the user has not used our site before. However, if user A tries to sign-up user B on the same computer, they end up changing their own details, rather than adding a new user account. 

I wonder if there is a way to add to the top of the Communication Preferences page a link similar to an event registration that says "Welcome User Name. (Not User Name, or want to register a different person?)" which would then create a new user and individual checksum etc? 

Sorry for my long explanation. Thanks for any feedback!

**Comment by TerryVeda** [comment]
If the email address is on the DB, then that contact record will be updated.  If the email address is not on the database, then a new contact record will be created.  Generally, it is best if users make sure that they are logged out before allowing other users on the same device.
