### ISSUE TITLE
Crashes on contribution "thank you" page

### ISSUE THREAD

**Issue by robbrandt** [veda-consulting/uk.co.vedaconsulting.gdpr#149]
We've had your extension installed for a month or two and just discovered that it's crashing on the Thank You page.  The transactions complete, and the members are getting their receipt and other confirmations, so apparently no one thought to report it. When we disable the GDPR extension the issue goes away.  Here's the stack trace:

#0 /mypath/public_html/sites/all/modules/civicrm/CRM/Core/Error.php(374): CRM_Core_Error::backtrace()
#1 /mypath/public_html/sites/all/modules/civicrm/CRM/Core/DAO.php(1094): CRM_Core_Error::fatal()
#2 /mypath/public_html/sites/all/civicrm_estensions/uk.co.vedaconsulting.gdpr/gdpr.php(259): CRM_Core_DAO::getFieldValue("CRM_Contribute_DAO_Contribution", NULL, "contact_id", "trxn_id")
#3 /mypath/public_html/sites/all/modules/civicrm/CRM/Utils/Hook.php(274): gdpr_civicrm_buildForm("CRM_Contribute_Form_Contribution_ThankYou", Object(CRM_Contribute_Form_Contribution_ThankYou))
#4 /mypath/public_html/sites/all/modules/civicrm/CRM/Utils/Hook/DrupalBase.php(85): CRM_Utils_Hook->runHooks((Array:62), "civicrm_buildForm", 2, "CRM_Contribute_Form_Contribution_ThankYou", Object(CRM_Contribute_Form_Contribution_ThankYou), NULL, NULL, NULL, NULL)
#5 /mypath/public_html/sites/all/modules/civicrm/Civi/Core/CiviEventDispatcher.php(90): CRM_Utils_Hook_DrupalBase->invokeViaUF(2, "CRM_Contribute_Form_Contribution_ThankYou", Object(CRM_Contribute_Form_Contribution_ThankYou), NULL, NULL, NULL, NULL, "civicrm_buildForm")
#6 [internal function](): Civi\Core\CiviEventDispatcher::delegateToUF(Object(Civi\Core\Event\GenericHookEvent), "hook_civicrm_buildForm", Object(Civi\Core\CiviEventDispatcher))
#7 /mypath/public_html/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func((Array:2), Object(Civi\Core\Event\GenericHookEvent), "hook_civicrm_buildForm", Object(Civi\Core\CiviEventDispatcher))
#8 /mypath/public_html/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch((Array:1), "hook_civicrm_buildForm", Object(Civi\Core\Event\GenericHookEvent))
#9 /mypath/public_html/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php(170): Symfony\Component\EventDispatcher\EventDispatcher->dispatch("hook_civicrm_buildForm", Object(Civi\Core\Event\GenericHookEvent))
#10 /mypath/public_html/sites/all/modules/civicrm/Civi/Core/CiviEventDispatcher.php(47): Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch("hook_civicrm_buildForm", Object(Civi\Core\Event\GenericHookEvent))
#11 /mypath/public_html/sites/all/modules/civicrm/CRM/Utils/Hook.php(164): Civi\Core\CiviEventDispatcher->dispatch("hook_civicrm_buildForm", Object(Civi\Core\Event\GenericHookEvent))
#12 /mypath/public_html/sites/all/modules/civicrm/CRM/Utils/Hook.php(426): CRM_Utils_Hook->invoke((Array:2), "CRM_Contribute_Form_Contribution_ThankYou", Object(CRM_Contribute_Form_Contribution_ThankYou), NULL, NULL, NULL, NULL, "civicrm_buildForm")
#13 /mypath/public_html/sites/all/modules/civicrm/CRM/Core/Form.php(576): CRM_Utils_Hook::buildForm("CRM_Contribute_Form_Contribution_ThankYou", Object(CRM_Contribute_Form_Contribution_ThankYou))
#14 /mypath/public_html/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Display.php(92): CRM_Core_Form->buildForm()
#15 /mypath/public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Display->perform(Object(CRM_Contribute_Form_Contribution_ThankYou), "display")
#16 /mypath/public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Contribute_Form_Contribution_ThankYou), "display")
#17 /mypath/public_html/sites/all/civicrm_estensions/biz.jmaconsulting.grantapplications/CRM/Core/Controller.php(351): HTML_QuickForm_Page->handle("display")
#18 /mypath/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(310): CRM_Core_Controller->run((Array:3), NULL)
#19 /mypath/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:15))
#20 /mypath/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#21 /mypath/public_html/sites/all/modules/civicrm/drupal/civicrm.module(448): CRM_Core_Invoke::invoke((Array:3))
#22 [internal function](): civicrm_invoke("contribute", "transact")
#23 /mypath/public_html/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2))
#24 /mypath/public_html/index.php(21): menu_execute_active_handler()
#25 {main}

**Comment by robbrandt** [comment]
It is the 2.6 release we are using.

**Comment by veda-consulting** [comment]
@rajeshrhino I think this is the issue we've fixed  recently? Could you confirm?

**Comment by rajeshrhino** [comment]
@veda-consulting This fix is in master branch. The next release should have the fix.

@robbrandt You can patch version 2.6 until the next version is released. Here is the patch https://github.com/veda-consulting/uk.co.vedaconsulting.gdpr/commit/937f4125d5f738754f7905842c1e80a08d46a1a7#diff-524307ffb175bf7a6f9245fa19cf78a5

**Comment by robbrandt** [comment]
How stable is the master branch?  Or how soon will the new release come?

My installation is of the last release, but it's missing the option to have a URL for the privacy policy.
https://github.com/veda-consulting/uk.co.vedaconsulting.gdpr/issues/125

So I think installing master will fix both of those things.

**Comment by veda-consulting** [comment]
@robbrandt we're looking at the end of this week for the next release. Master is pretty stable.

**Comment by robbrandt** [comment]
Is a release pending?  I'd rather use a release than master.

**Comment by TerryVeda** [comment]
A new release is being tested at the moment.  However, there are a couple of issues.  

More later

**Comment by veda-consulting** [comment]
Will be in 2.7, closing for now.

**Comment by alarmingcod** [comment]
We've just found this on a couple of sites is there an estimated release date for 2.7 yet?

**Comment by mikantchap** [comment]
Would also prefer to use 2.7
