### ISSUE TITLE
"Terms and Conditions" prompt not working for WordPress

### ISSUE THREAD

**Issue by madhavimalgaonkar** [veda-consulting/uk.co.vedaconsulting.gdpr#15]
I'am using latest version Civicrm-4.7.30 with wordpress-4.9.4. If I check the "Show the CiviCRM acceptance form" the site gives error (See the below attached screenshot)
![image](https://user-images.githubusercontent.com/30790755/37146033-a12f04b8-22e8-11e8-9df0-31b328503b1e.png).
**In the console:** The error is ` Failed to load resource: the server responded with a status of 404 (Not Found)`. And when clicked on `/civicrm/sla/accept?snippet=json` this link it says `The requested URL /civicrm/sla/accept was not found on this server.`

**Comment by veda-consulting** [comment]
This setting has been removed from the current release, we're bundling this in with the communication preferences.
