### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by gibsonoliver** [veda-consulting/uk.co.vedaconsulting.gdpr#153]
Documentation: 
Hi can the documentation be updated so the link  to the civicrm/gdpr/dashboard is included.
Found this hard to find

Cheers
Olly

**Comment by veda-consulting** [comment]
@gibsonoliver I think you've submitted a PR for this? Ok to close?

**Comment by gibsonoliver** [comment]
Yes please

Olly
