### ISSUE TITLE
GDPR Status shows first rather than latest

### ISSUE THREAD

**Issue by TerryVeda** [veda-consulting/uk.co.vedaconsulting.gdpr#164]
The GDPR Status shows the date the preferences were first set rather than the latest.  

![image](https://user-images.githubusercontent.com/43813309/46412118-7f5f6900-c715-11e8-893c-2c16e078b343.png)

**Comment by mathavanveda** [comment]
GDPR Status shows the last acceptance date on contact summary. GDPR acceptance for the above contact is 24 Sep 2018.
 
![gdpr latest acceptance](https://user-images.githubusercontent.com/6152709/46799841-cd93ee00-cd4d-11e8-884e-eda959c7e3be.png)

**Comment by mathavanveda** [comment]
The latest activity has wrong target contact, that's the reason you are not seeing latest acceptance date (3rd October 2018).

**Comment by mathavanveda** [comment]
Steps to Update Communication preference Offline 
1) Go to contact summary >> Action >> communication preference link
<img width="1104" alt="screenshot 2018-10-11 at 12 57 08 pm" src="https://user-images.githubusercontent.com/6152709/46807334-93cce280-cd61-11e8-96cf-670c6054171c.png">

2) For offline, If you are updating the communication preference behave of someone, you would see an extra field called 'Source of Communication preference' (which will store in activity details), this field will only appear if you are updating preference for someone. and update all the required fields and preferences and make sure data policy has been accepted.
<img width="1319" alt="screenshot 2018-10-11 at 12 58 13 pm" src="https://user-images.githubusercontent.com/6152709/46807382-b0691a80-cd61-11e8-9603-954f80eb16fc.png">

3) For offline update, activity source contact would be the logged in user and target contact would be the actual contact who you want to update the preferences.
![sourcecontact](https://user-images.githubusercontent.com/6152709/46808018-3b96e000-cd63-11e8-961a-7d59810700b7.png)

**Comment by veda-consulting** [comment]
@TerryVeda if you can ensure we add this to the documentation, it was a key request coming in from users of CiviCRM.
