### ISSUE TITLE
"I accept the Terms & Conditions for this event."

### ISSUE THREAD

**Issue by robbrandt** [veda-consulting/uk.co.vedaconsulting.gdpr#165]
But it's not an event, it's a donation. I think this text just needs to be generalized to fit both events, contributions and profile submissions (when you support that).

**Comment by mathavanveda** [comment]
Hi @robbrandt , 

fixed the default text which used as default settings for both contribution pages and events. 

Terms and Condition in GDPR Setting page is commonly used for both Contribution pages and Events
![commonsettingsforeventordonation](https://user-images.githubusercontent.com/6152709/46820470-2c715b80-cd7e-11e8-99d8-1e451adf785f.png)

but you can also modify the Label text and Terms and condition file more specific to contribution page and event using this setting. 
Create/Edit Contribution page / Event, you can able to see custom tab called 'Terms and conditions'. You can enable this settings and attach the Terms and condition file and you can able to modify the check box text and link label more specific to this contribution page / Event.

Example
![settingperpage](https://user-images.githubusercontent.com/6152709/46820545-5c206380-cd7e-11e8-90ee-681215c10d4e.png)

**Comment by robbrandt** [comment]
Thank you!  I hadn't noticed that before!
