### ISSUE TITLE
CiviCRM 5.3.2 - (uk.co.vedaconsulting.gdpr)	2.6 - Sorry, due to an error, we are unable to fulfill your request at the moment.

### ISSUE THREAD

**Issue by kumarvt** [veda-consulting/uk.co.vedaconsulting.gdpr#174]
upgrade to CiviCRM 5.3.2 - broke contribution form upon submission - the full trace is attched in file

***BACKTRACE***
#0 /opt/bitnami/apps/civicrm/htdocs/sites/default/files/civicrm/ext/ca.bidon.reporterror/CRM/ReportError/Utils.php(31): reporterror_civicrm_generatereport("xxxxxx xxxxxxx xxxxx", (Array:2), NULL, (Array:0))
#1 /opt/bitnami/apps/civicrm/htdocs/sites/default/files/civicrm/ext/ca.bidon.reporterror/CRM/ReportError/Handler/FormsNoReferer.php(54): CRM_ReportError_Utils::sendReport((Array:2), (Array:0))
#2 /opt/bitnami/apps/civicrm/htdocs/sites/default/files/civicrm/ext/ca.bidon.reporterror/reporterror.php(168): CRM_ReportError_Handler_FormsNoReferer::handler((Array:2), (Array:0))
#3 /opt/bitnami/apps/civicrm/htdocs/sites/all/modules/civicrm/CRM/Core/Error.php(368): reporterror_civicrm_handler((Array:2))
#4 /opt/bitnami/apps/civicrm/htdocs/sites/all/modules/civicrm/CRM/Core/DAO.php(1153): CRM_Core_Error::fatal()
#5 /opt/bitnami/apps/civicrm/htdocs/sites/default/files/civicrm/ext/uk.co.vedaconsulting.gdpr-2.3/gdpr.php(259): CRM_Core_DAO::getFieldValue("CRM_Contribute_DAO_Contribution", NULL, "contact_id", "trxn_id")
#6 /opt/bitnami/apps/civicrm/htdocs/sites/all/modules/civicrm/CRM/Utils/Hook.php(274): gdpr_civicrm_buildForm("CRM_Contribute_Form_Contribution_ThankYou", Object(CRM_Contribute_Form_Contribution_ThankYou))
#7 /opt/bitnami/apps/civicrm/htdocs/sites/all/modules/civicrm/CRM/Utils/Hook/DrupalBase.php(84): CRM_Utils_Hook->runHooks((Array:53), "civicrm_buildForm", 2, "CRM_Contribute_Form_Contribution_ThankYou", Object(CRM_Contribute_Form_Contribution_ThankYou), NULL, NULL, NULL, NULL)
#8 /opt/bitnami/apps/civicrm/htdocs/sites/all/modules/civicrm/Civi/Core/CiviEventDispatcher.php(90): CRM_Utils_Hook_DrupalBase->invokeViaUF(2, "CRM_Contribute_Form_Contribution_ThankYou", Object(CRM_Contribute_Form_Contribution_ThankYou), NULL, NULL, NULL, NULL, "civicrm_buildForm")
#9 [internal function](): Civi\Core\CiviEventDispatcher::delegateToUF(Object(Civi\Core\Event\GenericHookEvent), "hook_civicrm_buildForm", Object(Civi\Core\CiviEventDispatcher))
#10 /opt/bitnami/apps/civicrm/htdocs/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func((Array:2), Object(Civi\Core\Event\GenericHookEvent), "hook_civicrm_buildForm", Object(Civi\Core\CiviEventDispatcher))
#11 /opt/bitnami/apps/civicrm/htdocs/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch((Array:1), "hook_civicrm_buildForm", Object(Civi\Core\Event\GenericHookEvent))
#12 /opt/bitnami/apps/civicrm/htdocs/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php(167): Symfony\Component\EventDispatcher\EventDispatcher->dispatch("hook_civicrm_buildForm", Object(Civi\Core\Event\GenericHookEvent))
#13 /opt/bitnami/apps/civicrm/htdocs/sites/all/modules/civicrm/Civi/Core/CiviEventDispatcher.php(47): Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch("hook_civicrm_buildForm", Object(Civi\Core\Event\GenericHookEvent))
#14 /opt/bitnami/apps/civicrm/htdocs/sites/all/modules/civicrm/CRM/Utils/Hook.php(164): Civi\Core\CiviEventDispatcher->dispatch("hook_civicrm_buildForm", Object(Civi\Core\Event\GenericHookEvent))
#15 /opt/bitnami/apps/civicrm/htdocs/sites/all/modules/civicrm/CRM/Utils/Hook.php(425): CRM_Utils_Hook->invoke((Array:2), "CRM_Contribute_Form_Contribution_ThankYou", Object(CRM_Contribute_Form_Contribution_ThankYou), NULL, NULL, NULL, NULL, "civicrm_buildForm")
#16 /opt/bitnami/apps/civicrm/htdocs/sites/all/modules/civicrm/CRM/Core/Form.php(595): CRM_Utils_Hook::buildForm("CRM_Contribute_Form_Contribution_ThankYou", Object(CRM_Contribute_Form_Contribution_ThankYou))
#17 /opt/bitnami/apps/civicrm/htdocs/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Display.php(92): CRM_Core_Form->buildForm()
#18 /opt/bitnami/apps/civicrm/htdocs/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Display->perform(Object(CRM_Contribute_Form_Contribution_ThankYou), "display")
#19 /opt/bitnami/apps/civicrm/htdocs/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Contribute_Form_Contribution_ThankYou), "display")
#20 /opt/bitnami/apps/civicrm/htdocs/sites/all/modules/civicrm/CRM/Core/Controller.php(351): HTML_QuickForm_Page->handle("display")
#21 /opt/bitnami/apps/civicrm/htdocs/sites/all/modules/civicrm/CRM/Core/Invoke.php(309): CRM_Core_Controller->run((Array:3), NULL)
#22 /opt/bitnami/apps/civicrm/htdocs/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:15))
#23 /opt/bitnami/apps/civicrm/htdocs/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#24 /opt/bitnami/apps/civicrm/htdocs/sites/all/modules/civicrm/drupal/civicrm.module(445): CRM_Core_Invoke::invoke((Array:3))
#25 /opt/bitnami/apps/civicrm/htdocs/includes/menu.inc(527): civicrm_invoke("contribute", "transact")
#26 /opt/bitnami/apps/civicrm/htdocs/index.php(21): menu_execute_active_handler()
#27 {main}

[uk.co.vedaconsulting.gdpr-2.3_full_trace_error.txt](https://github.com/veda-consulting/uk.co.vedaconsulting.gdpr/files/2549389/uk.co.vedaconsulting.gdpr-2.3_full_trace_error.txt)

**Comment by Upperholme** [comment]
See #149

**Comment by deepak-srivastava** [comment]
backtrace is showing that it's the "ca.bidon.reporterror" extension thats failing not gdpr. 
And 2.7 release is out anyway.
