### ISSUE TITLE
The GDPR menu items are missing 

### ISSUE THREAD

**Issue by AlphaDE** [veda-consulting/uk.co.vedaconsulting.gdpr#185]
Just installed v2.7 of the GDPR plugin with CiviCRM 5.8.1 with German language, all plguin menu items are still missing as with previous versions. After applying my rejected patch in gdpr_civicrm_navigationMenu function, the menu items appear. Possibly the hardcoded English names for the menu entries in the plugin do not work with German localization. With my patch (see pull request), it does work where the problem is described in detail.

**Comment by deepak-srivastava** [comment]
See my reply on #92 and #186. Think it's same problem.

**Comment by AlphaDE** [comment]
Tracking down #92 I disabled currently not used CiviCRM plugins like

SEPA Direct Debit and CiviBanking

After doing that, some issues with the CiviCRM menu bar disappeared and the GDPR menu item under contacts is now also shown properly.

So side effect with other plugins
