### ISSUE TITLE
Confirmation of data protection/terms&conditions not recognized

### ISSUE THREAD

**Issue by AlphaDE** [veda-consulting/uk.co.vedaconsulting.gdpr#186]
Using CiviCRM 5.8.1 with German localization, registering a participant in CiviEvent (live registratiion) is not possible with data protection rules/terms&conditions enabled. Although both boxes were ticked, one is thrown back to the main registration page with the error, that these two fields are mandatory. In the test environment, it works. 

Also the positioning at the bottom of the form is not honored in the live registration form, it does work in the test form.

**Comment by deepak-srivastava** [comment]
@AlphaDE see my reply on #92 - seems like you got some customization (theme or js) which on frontend pages causing the problem.
What you calling "test environment" is civicrm backend - and because there are no js failures - it works fine.

**Comment by AlphaDE** [comment]
See https://github.com/veda-consulting/uk.co.vedaconsulting.gdpr/issues/92 for the solution
