### ISSUE TITLE
Version 2.0 creates custom field set extending missing activity type: Event Terms and Conditions Acceptance

### ISSUE THREAD

**Issue by davejenx** [veda-consulting/uk.co.vedaconsulting.gdpr#20]
Version 2.0 creates custom field set "Event terms and conditions acceptance", which extends activity type "Event Terms and Conditions Acceptance". However the extension doesn't seem to create this activity type: it didn't do so on upgrade from version 1.0 and a quick search through the v2.0 code didn't find anything creating this activity type.

In Civi 4.6.33, the consequence was fatal errors throughout Civi:
Invalid Entity Filter in CRM_Core_BAO_CustomGroup::validateSubTypeByEntity() (line 643 of ...CRM/Core/BAO/CustomGroup.php)
because the custom field set extends a non-existent entity subtype.

How should the activity type have been created, did we miss a manual step?

**Comment by veda-consulting** [comment]
@davejenx thanks for the bug report, we're due to release some patches today and will include this.

**Comment by Upperholme** [comment]
Just updating the Drupal Views module (3.19 has just been released) on a site with this extension installed, and the whole thing crashed when I ran update.php
Same fatal error reported. Disabled the GDPR extension and the update ran fine.

**Comment by veda-consulting** [comment]
@Upperholme thanks for the pointer, I believe we have this resolved and the guys are testing as we speak. Will confirm when we're done.

**Comment by veda-consulting** [comment]
@Upperholme @davejenx we've released v2.1, please try that
Note that if it doesn't upgrade cleanly (depends on which version you were on prior to upgrade) there may be some tweaking needed to the tables to get it to cleanly work. From v2 it should upgrade cleanly.
