### ISSUE TITLE
4.6 compatibility

### ISSUE THREAD

**Issue by ufundo** [veda-consulting/uk.co.vedaconsulting.gdpr#3]
Hi,

Really interested in this functionality but running 4.6.

Would there be much involved in making compatible? Would be up for trying to help with this if pointed in right direction.

Thanks!

**Comment by veda-consulting** [comment]
@ufundo we have a couple of clients on 4.6 so we may try and make it backward compatible but it would be good if you could jump on. Have you tried it in 4.6?

**Comment by ufundo** [comment]
Hi Parvez,

Cool. I haven't tried it yet - but can give it a go and let you know how it
goes.

**Comment by veda-consulting** [comment]
@ufundo please do, let us know how you get on.

**Comment by nishant-bhorodia** [comment]
Hey @ufundo did you get a chance to test this with 4.6? Thanks.

**Comment by ufundo** [comment]
@nishant-bhorodia sorry, not yet! Still intend to but don't know when I will have the time.

**Comment by omarabuhussein** [comment]
It does not work on 4.6, there are some issues but I fixed them in this PR : 

https://github.com/veda-consulting/uk.co.vedaconsulting.gdpr/pull/9 

@veda-consulting

**Comment by veda-consulting** [comment]
@omarabuhussein great work, have accepted the changes
@ufundo @nishant-bhorodia try the latest release
Note we'll be making this an official release this week i.e. it will show up in the extensions listing in your CiviCRM etc
