### ISSUE TITLE
Missing table during/after updating to 2.0

### ISSUE THREAD

**Issue by y3kdaniel** [veda-consulting/uk.co.vedaconsulting.gdpr#31]
During the update to 2.0 I got "Missing Table" messages, and in the debug out put during certain routines (in this case I disabled an extension not related to this) I get:

>  Error Code: Table 'dgt_friends.civicrm_value_contribution_page_terms_and_conditions_7' doesn't exist, 

The only reference I can find to "civicrm_value_contribution_page_terms_and_conditions_7" is in xml/CustomGroupData.xml

Is this a bug or just something gone wrong on my end?
Is there a way to fix this? Can I create the table manually?

**Comment by veda-consulting** [comment]
@y3kdaniel we've reproduced this issue. You can create the table as per the SQL below and retry the upgrade.

CREATE TABLE IF NOT EXISTS `civicrm_value_contribution_page_terms_and_conditions_7` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Default MySQL primary key',
  `entity_id` int(10) unsigned NOT NULL COMMENT 'Table that this extends',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_entity_id` (`entity_id`),
  CONSTRAINT `FK_civicrm_value_contribution_page__b28312db428f5bbd` FOREIGN KEY (`entity_id`) REFERENCES `civicrm_contribution_page` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

We think running a cache clear prior to upgrade may avoid this but for now running the table statement should get you upgraded. I would do a pull before upgrade too if your taking it from master.

**Comment by y3kdaniel** [comment]
Created the table using the above and did another pull, all seems to be working okay so far!

**Comment by veda-consulting** [comment]
@y3kdaniel thanks, we've released 2.1 today, closing this issue
