### ISSUE TITLE
Error: Class 'CRM_Gdpr_SLA_utils' not found in gdpr_civicrm_pageRun()

### ISSUE THREAD

**Issue by magnolia61** [veda-consulting/uk.co.vedaconsulting.gdpr#32]
First of all, thanks for all the updates> Great module!

Just reporting: After installing and upgrading to 2.0 I get the following fatal error when I go to a contact"
Error: Class 'CRM_Gdpr_SLA_utils' not found in gdpr_civicrm_pageRun() (line 467 of /var/www/vhosts/xyz/webroot/sites/all/modules/civicrm_extensions/uk.co.vedaconsulting.gdpr/gdpr.php).

**Comment by veda-consulting** [comment]
@magnolia61 we have a fix for this. We'll be releasing a patched version later today.

**Comment by veda-consulting** [comment]
@magnolia61 fix is in the latest release, please try and confirm.
