### ISSUE TITLE
Change activity types to monitor

### ISSUE THREAD

**Issue by jorich-2000** [veda-consulting/uk.co.vedaconsulting.gdpr#5]
Cant go back into settings to change the DPO or interaction types

**Comment by veda-consulting** [comment]
@jorich-2000 could you supply a bit more information on the version of CiviCRM and which CMS you're doing this on please?

**Comment by jorich-2000** [comment]
Wordpress 4.8.2Civicrm 4.7.23.PHP 7.0.24 
ExtensionsAll extensions are up-to-date:API Key Management (com.cividesk.apikey) version 1.2CiviMobile (com.webaccessglobal.module.civimobile) version 2.0CSV Import Helper (uk.artfulrobot.civicrm.importhelper) version 1.1.2-betaGeneral Data Protection Regulation (uk.co.vedaconsulting.gdpr) version 1.0Mailchimp (uk.co.vedaconsulting.mailchimp) version 2.0.1CiviOutlook API (uk.co.vedaconsulting.outlookapi) version 2.1

The GDPR dashboard shows which activities I set to monitor when first opening - but how do i change them - the GDPR Settings section is blank.Let me know if you want me to do any testing as I am quite happy to assist - this is going to be an invaluable extension



 Regards, Jonathan Richardson------------------------------------------------------------------ *** CONFIDENTIALITY NOTICE *** The information in this e-mail message may be confidential and is for use of only the named recipient. If you are not the intended recipient the retention, dissemination, distribution or copying of this e-mail message is strictly prohibited.

**Comment by veda-consulting** [comment]
@jorich-2000 we cant reproduce this in the 2.0 branch. We're going to release a 2.1 later today or early tomorrow, might be worth trying in that once its released.
