### ISSUE TITLE
Link and URL Tokens not working when used in CiviMail with WP

### ISSUE THREAD

**Issue by kcristiano** [veda-consulting/uk.co.vedaconsulting.gdpr#50]
Using CiviCRM 5.0.0, WP 4.9.5

On email delivery the tokens are not translated and appear as such:

{contact.comm_pref_supporter_link}

{contact.comm_pref_supporter_url}

Creating an image with the URL link creates a non-clickable image.

**Comment by kcristiano** [comment]
I was able to create a manual link 

`https://example.org/wp-civicrm-basepage/?page=CiviCRM&q=civicrm/gdpr/comms-prefs/update&reset=1&{contact.checksum}&cid={contact.contact_id}`

and that does work.

**Comment by veda-consulting** [comment]
@kcristiano thanks, we'll add to our queue

**Comment by veda-consulting** [comment]
@kcristiano to confirm are you using Mosaico?

**Comment by kcristiano** [comment]
No,  I am not using Mosaico.

**Comment by veda-consulting** [comment]
@kcristiano we have the fix for wpbasepage pencilled in for 2.2 (due out friday)

We've tried single emails and they render the URL ok, trying out mass mailing now.

**Comment by kcristiano** [comment]
Perfect I will test as soon as the release is done.  Thank you

**Comment by veda-consulting** [comment]
@kcristiano we now have a new set of tokens, that can be used in mass mailing. This change will go out in the 2.2 release scheduled for Friday.

**Comment by veda-consulting** [comment]
@kcristiano we've pushed the release a bit early as the mass email token issue affects most installs. Please do give it a test when you get a chance, closing this issue for now.

**Comment by kcristiano** [comment]
I have tested with the built in mailer.   Both tokens now work.  I have not tested with Mosaico as we do not have that in production.

**Comment by veda-consulting** [comment]
@kcristiano great, thanks
