### ISSUE TITLE
Actions dropdown disabled with selected record only

### ISSUE THREAD

**Issue by Czollli** [veda-consulting/uk.co.vedaconsulting.gdpr#56]
Hi,
one of our clients have just reported this which I could confirm on two different sites:

"On the GDPR dashboard, clicking on the reported number of no-activity contacts brings up a search page with those contacts listed in the expected manner.  For the Actions drop down menu, selecting All nnnn records makes the menu becomre active, but selecting individual records and ticking the "Selected records" button does not cause the count of selected records to count the number of selected records and the Actions menu does not become active.  Something not working there, I think."

At that time they were on v2.1 but an updated to v2.2 did not help either.

Thanks

**Comment by veda-consulting** [comment]
@Czollli ok thanks, we'll take a look. We have a few higher priority issues on the queue at the moment.

**Comment by Czollli** [comment]
Thanks a lot for fixing
