### ISSUE TITLE
Contact GDPR Tab to only display public group history

### ISSUE THREAD

**Issue by veda-consulting** [veda-consulting/uk.co.vedaconsulting.gdpr#61]
Currently the tab shows all group history
It would make more sense if it only showed public group history as these are the only options available on the communication preferences page.

**Comment by veda-consulting** [comment]
Will be in 2.3

**Comment by tbuytaer** [comment]
On the other hand, it is also a useful feature to show the history of all the groups.

Could this maybe be something we can toggle?
Above the group history put a checkbox "Public groups only".
This could be checked by default, but if someone wants to see a history of all the groups, they can uncheck it and see everything.
