### ISSUE TITLE
Fatal error when event registered

### ISSUE THREAD

**Issue by Czollli** [veda-consulting/uk.co.vedaconsulting.gdpr#62]
Hi,

Fatal error: Call to undefined method CRM_Utils_System::getUrlPath() in /home/rebripug/drupal-7.58/sites/redbridgecvs.net/civicrm_extensions/uk.co.vedaconsulting.gdpr-master/gdpr.php on line 274

There is indeed no occurence of method in CRM/Utils/System.php on neither 4.6 nor 4.7.

Please have a look.
Thanks

**Comment by veda-consulting** [comment]
Note that the method was available in 4.7.30 but nothing previous, hence its been removed in favour of a more backward compatible approach.

**Comment by Czollli** [comment]
Thanks a lot, it is working fine
