### ISSUE TITLE
Groups which are Added (by ) is not listed on GDPR tab

### ISSUE THREAD

**Issue by mathavanveda** [veda-consulting/uk.co.vedaconsulting.gdpr#66]

**Comment by veda-consulting** [comment]
@mathavanveda so any group subscription for which we cant find an audit logging entry for wont be shown. I think we should push this question out to the community i.e. what would they like to see.

1. Keep it as it is - in the GDPR sense we dont know when the person subscribed to the group so cant show the row
2. Use the latest date on the group contact table as an assumption to when they were added
3. Recommend logging is turned on and re-enabled to initialise any missing log entries

**Comment by veda-consulting** [comment]
Closing this
