### ISSUE TITLE
GDPR extension installation error on Drupal7/Civi 4.7.31

### ISSUE THREAD

**Issue by TomCrawshaw** [veda-consulting/uk.co.vedaconsulting.gdpr#68]
We're really looking forward to using this valuable extension, and thanks for working on it, but installing the extension (version 2.3, 19-04-2018) results in a rather unhelpful database error:

"Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
DB Error: already exists"

Then, returning to the Home page, and clicking on CiviCRM, I get an alert:
 "Found name, activity_type, civicrm_option_group"

The extension appears to be installed, and Dashboard settings can be filled in, but choosing the GDPR tab in a contact screen give an alert:

"Network Error
Unable to reach the server. Please refresh this page in your browser and try again." and a error message in the log as in the attached file

Any ideas?

[GDPR error message.txt](https://github.com/veda-consulting/uk.co.vedaconsulting.gdpr/files/1935870/GDPR.error.message.txt)

**Comment by veda-consulting** [comment]
@TomCrawshaw was it a fresh install i.e. you installed the latest v2.3 without any prior installs?

**Comment by Upperholme** [comment]
I've just now done a fresh install (i.e. no prior versions of GDPR extension had been installed previously), on a D7/Civi 5.0 site. No errors.
Got the little alert message: ""Found name, activity_type, civicrm_option_group"
On viewing the GDPR tab on a contact record, no errors.

**Comment by TomCrawshaw** [comment]
No, I’d installed an earlier version. Do I have to delete something in a table as well as uninstalling?

Tom

**Comment by TomCrawshaw** [comment]
I can add that I've now installed the 2.3 version in a D7/Civi 4.7.27 site which never had the earlier version installed, and it seems better (still got the "Found name, activity_type, civicrm_option_group" alert). On viewing GDPR tab no errors.  I could probably totally delete my Test instance, but I'd really like to know if there is a less drastic way

**Comment by veda-consulting** [comment]
@TomCrawshaw hi - we have seen this in the past when there is an upgrade from beta or early release to a later stable version. We might have some pointers on what you can try but the easiest thing would be to totally uninstall and try again. If you'd prefer not to do that we could probably throw out some pointers but wouldn't be able to support you through the process as such. Please do let us know.
