### ISSUE TITLE
Option to optout bulkmails

### ISSUE THREAD

**Issue by magnolia61** [veda-consulting/uk.co.vedaconsulting.gdpr#70]
Hello, currently it is possible from the comm pref page to unsubscribe from mailing groups.

Sometimes opting out of bulk mails would be the desired action. Opt out of bulk mails will keep transnational mails possible, which is a very realistic scenario for many organizations.

There are two settings for this:
1. a general one for the contact at communication preferences (no bulk emails?)
2. a setting per email adres (Bluk mailings?)

Would it be possible to add a general optout for bulk mails or per email somewhere on the comm pref page as well?

**Comment by veda-consulting** [comment]
@magnolia61 if you make the channels available in the comms preferences settings then when the user de-selects email this effectively opts them out of bulk emails. There isn't any way for the supporter to set no emails at all at the moment from the comms preferences page as when they register for an event or make a donation the transactional email needs to be sent. Does that help?

**Comment by magnolia61** [comment]
I can see two enhancements:
1) connect the de-select of email and the general no-bulkmail setting so they match
2) enable a way to de-select 'receive bulk mails' per email in the comm pref page

**Comment by TerryVeda** [comment]
Bulk email flag is to indicate which email address should be used for bulk email - if bulk emails are permitted.
