### ISSUE TITLE
Some tokens not working when this extension is enabled

### ISSUE THREAD

**Issue by magnolia61** [veda-consulting/uk.co.vedaconsulting.gdpr#73]
When this extension is enabled some system tokens stop working (both in 2.3 and current master)
Our most important being:` {contact.email_greeting}`
But I will check for more.
Strangely enough it is not an all-or-nothing situation: `{contact.first_name}` works ok

probably related to: https://github.com/mathavanveda/uk.co.vedaconsulting.gdpr/commit/7cda26751efc406659a0ad521674935d267c70fc ?
Would this approach form the civitoken extension be helpfull? https://github.com/kainuk/nz.co.fuzion.civitoken/commit/47d511799b93b371367fb17e6aafb76f162f9c65

**Comment by mathavanveda** [comment]
Hi @magnolia61 , 

Could you please provide us more details about which CiviCRM version and how do you send email / Print PDF etc (Steps to reproduce this issue).

**Comment by magnolia61** [comment]
Not at home at the moment to make screenshots but its both Scheduled mails and civirules sent mails. When I send manually the token(s) work ok.

**Comment by veda-consulting** [comment]
@magnolia61 looks like it seems to break scheduled reminder tokens. We're taking a look and release a fix in 2.4 for the issue once we've found it.

**Comment by veda-consulting** [comment]
Released 2.4

**Comment by magnolia61** [comment]
for reference, tokens for emails sent by CiviRules do not work yet. Only Scheduled Action Reminders work
