### ISSUE TITLE
Missing T&C tab on Contributions in 4.6

### ISSUE THREAD

**Issue by marsh-circle** [veda-consulting/uk.co.vedaconsulting.gdpr#78]
On visiting the Edit Contribution Page pages in 4.6, there is no T&C tab at the top.
It's there for events, but not for Contributions.

File is uploaded andall other settings appear to be working - just no this one.

I can see the tab on a 4.7

- nothing in Broswer console
- nothing in ConfigAndLog
- nothing in php / webserver logs
 
Is there a simple fix?

**Comment by mathavanveda** [comment]
this is resolved and related issue https://github.com/veda-consulting/uk.co.vedaconsulting.gdpr/pull/79

**Comment by marsh-circle** [comment]
OK - sorry - didn't see that in a search.

Thanks for update and fix though!! :) :)

**Comment by cmolava** [comment]
Hi, to get the tabs working on 4.6 there are a couple of steps:
First pull in the latest extension changes from master.

Then, you will need to modify a CiviCRM core file: CRM/Contribute/Form/ContributionPage/TabHeader.php.

Find the line (it should be line 138).:
`$contribPageId = $form->getVar('_id');`
Underneath that add a line:
`CRM_Utils_Hook::tabset('civicrm/admin/contribute', $tabs, array('contribution_page_id' => $contribPageId));`

You can either copy the file to your custom php directory or modify it directly. The line is included in 4.7+ so you need not worry about preserving the customisation.

**Comment by veda-consulting** [comment]
Released 2.4
