### ISSUE TITLE
Incorrect Data Policy file path stored in GDPR settings

### ISSUE THREAD

**Issue by oskylark** [veda-consulting/uk.co.vedaconsulting.gdpr#80]
function saveTCFile in /CRM/Gdpr/Form/Settings.php misses out a / in the file path when storing the uploaded data policy file.  This results in the link provided on the GDPR settings and the Communications Preferences pages not working.

Current line 302:
`      if ($saved) {
        return $this->getFileUrl($publicUploadDir . $fileName);
      }
`

whereas it should be as in the "file_exists" check earlier in the function (line 294):
`      if ($saved) {
        return $this->getFileUrl($publicUploadDir . '/' . $fileName);
      }
`

**Comment by veda-consulting** [comment]
Released 2.4
