### ISSUE TITLE
Confirm Payment button locks when terms not checked

### ISSUE THREAD

**Issue by magnolia61** [veda-consulting/uk.co.vedaconsulting.gdpr#84]
When the terms are used on a contribution page and a user does not check the boxes, the following occures:
1. a message is displayed
2. the 'Confirm Payment' button locks
3. after checking the boxes, the button is still locked as 'Processing'...
4. the user cannot continue

![screenshot from 2018-05-05 11-30-46](https://user-images.githubusercontent.com/2195908/39661792-fb6cbf96-5057-11e8-882b-0b0b4a0804d8.png)

**Comment by veda-consulting** [comment]
Released 2.4
