### ISSUE TITLE
Translation in transifex

### ISSUE THREAD

**Issue by alejandro-ixiam** [veda-consulting/uk.co.vedaconsulting.gdpr#86]
Hi guys, thanks for the work in this extension. I took the liberty of adding the .pot file to transifex so it can be translated

https://www.transifex.com/civicrm/civicrm_extensions/gdpr/

It is now fully translated to Spanish.

Cheers

**Comment by veda-consulting** [comment]
Hey @alejandro-ixiam , hope you're well. Thanks for this. Is there anything we need to do to include your translation?

**Comment by alejandro-ixiam** [comment]
Hi @veda-consulting , hope you're well too. Thanks for your answer! in fact, it seems that some of us are facing the same issue when trying to use the extension translated #93 #91 
We are also looking into this issue with @sluc23 to see if we can find a fix.

Thanks!

**Comment by veda-consulting** [comment]
@alejandro-ixiam ok, I can see Jaap has a potential solution. Let me know how you guys get on, we can get some resource onto it if needed.

**Comment by sluc23** [comment]
@veda-consulting the solution Jaap found didn't work for us, we have still same issue in CiviCRM 4.6 / Spanish. tx

**Comment by cuatrocento** [comment]
#91 I've applied the spanish translation and the issue continues. I will try with the Jaap solution.

**Comment by cuatrocento** [comment]
#91 Now it's working

**Comment by veda-consulting** [comment]
@sluc23 note we made a couple of 4.6 specific changes to 2.4 but the release didn't go out correctly so instead you can try 2.5. I feel some of the issues maybe clashing with each other, Jaap was around at the CiviCamp yesterday and was confident  his fix worked.

**Comment by alejandro-ixiam** [comment]
seems that Jaap fix is working now. Thanks all!
