### ISSUE TITLE
Why is there a limit on Data Policy acceptance period?

### ISSUE THREAD

**Issue by jeffcapeshop** [veda-consulting/uk.co.vedaconsulting.gdpr#87]
I'm confused about why there is a data policy acceptance period if the policy has not been altered, and why that period can vary between 6 and 60 months - is this actually a requirement of GDPR?

**Comment by veda-consulting** [comment]
@jeffcapeshop its not a requirement of GDPR per say but the advise we've been given is that organisations should review their data policy's every 2 or 3 years as a matter of best practice. Note that if your practices don't match what your data policy is conveying then your breaching your agreement with the data subject. Hence we're setting a time frame on the agreements. Worst case is in 5 years time you'll need to clone the existing one and re-upload, although I would recommend a 3 year review.
