### ISSUE TITLE
Fatal errors for Terms and Conditions pages

### ISSUE THREAD

**Issue by mikantchap** [veda-consulting/uk.co.vedaconsulting.gdpr#90]
Extension  2.3
CiviCrRM  4.6.36
Drupal  7.58
Using administrator role.

civicrm/admin/contribute/terms_conditions?reset=1 gives a fatal error:

Fatal error: Call to undefined method CRM_Custom_Form_CustomData::setGroupTree() in sites/default/files/civicrm/extensions/uk.co.vedaconsulting.gdpr/CRM/Gdpr/Form/ContributionPage/TermsAndConditions.php on line 25

civicrm/event/manage/terms_conditions?reset=1 gives a fata error:

Fatal error: Call to undefined method CRM_Custom_Form_CustomData::setGroupTree() in sites/default/files/civicrm/extensions/uk.co.vedaconsulting.gdpr/CRM/Gdpr/Form/ManageEvent/TermsAndConditions.php on line 28

The Ts and Cs tab on events gives a network error that is actually a 500 error:
civicrm/event/manage/terms_conditions?reset=1&action=update&id=7&component=event&snippet=json

**Comment by cmolava** [comment]
Hi @mikantchap, using the latest version from github should fix those issues.

**Comment by mikantchap** [comment]
I thinks thats 2.4 (?) but it still says 2.3 when you unzip it - it contains <version>2.3</version> in the info.xml.

**Comment by veda-consulting** [comment]
@mikantchap thanks for the feedback, we've upped the version numbers for the next set
