### ISSUE TITLE
Error for Communications Preferences Page

### ISSUE THREAD

**Issue by cuatrocento** [veda-consulting/uk.co.vedaconsulting.gdpr#91]
Extension 2.3
CiviCrRM 4.7.4
Drupal 7.55

CiviCRM_API3_Exception: "Failed encoding non-numeric value (#typeId)"

#0 /usr/home/.../web/sites/default/files/civicrm/extensions/uk.co.vedaconsulting.gdpr-2.3/CRM/Gdpr/SLA/Utils.php(119): civicrm_api3("Activity", "get", (Array:4))
#1 /usr/home/.../web/sites/default/files/civicrm/extensions/uk.co.vedaconsulting.gdpr-2.3/CRM/Gdpr/SLA/Utils.php(159): CRM_Gdpr_SLA_Utils::getContactLastAcceptance(7327)
#2 /usr/home/.../web/sites/default/files/civicrm/extensions/uk.co.vedaconsulting.gdpr-2.3/CRM/Gdpr/Form/UpdatePreference.php(123): CRM_Gdpr_SLA_Utils::isContactDueAcceptance(7327)
#3 /usr/home/.../web/sites/default/modules/civicrm/CRM/Core/Form.php(540): CRM_Gdpr_Form_UpdatePreference->buildQuickForm()
#4 /usr/home/.../web/sites/default/modules/civicrm/CRM/Core/QuickForm/Action/Display.php(92): CRM_Core_Form->buildForm()
#5 /usr/home/.../web/sites/default/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Display->perform(Object(CRM_Gdpr_Form_UpdatePreference), "display")
#6 /usr/home/.../web/sites/default/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Gdpr_Form_UpdatePreference), "display")
#7 /usr/home/.../web/sites/default/modules/civicrm/CRM/Core/Controller.php(351): HTML_QuickForm_Page->handle("display")
#8 /usr/home/.../web/sites/default/modules/civicrm/CRM/Utils/Wrapper.php(113): CRM_Core_Controller->run()
#9 /usr/home/.../web/sites/default/modules/civicrm/CRM/Core/Invoke.php(286): CRM_Utils_Wrapper->run("CRM_Gdpr_Form_UpdatePreference", "UpdatePreference", NULL)
#10 /usr/home/.../web/sites/default/modules/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:14))
#11 /usr/home/.../web/sites/default/modules/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:4))
#12 /usr/home/.../web/sites/default/modules/civicrm/drupal/civicrm.module(454): CRM_Core_Invoke::invoke((Array:4))
#13 [internal function](): civicrm_invoke("gdpr", "comms-prefs", "update")
#14 /usr/home/.../web/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:3))
#15 /usr/home/.../web/index.php(54): menu_execute_active_handler()
#16 {main}

**Comment by veda-consulting** [comment]
@cuatrocento are you still seeing this issue? have you seen the suggestions around the core patch?

**Comment by cuatrocento** [comment]
No, this issue is solved. Thks
