### ISSUE TITLE
Contact page gives a fatal error in CiviCRM 4.6 in Dutch

### ISSUE THREAD

**Issue by jaapjansma** [veda-consulting/uk.co.vedaconsulting.gdpr#93]
I have installed this extension in a CiviCRM 4.6, Dutch but when I want to view a contact card. 
I get the following error:

![screenshot from 2018-05-14 10-44-18](https://user-images.githubusercontent.com/4126292/39987079-f486a6de-5763-11e8-9355-1e7833419cbb.png)

This error has something to with retrieving the activity type id with the name of the activity.

**Comment by jaapjansma** [comment]
Proposed fix is to retrieve first the id of the SLA Acceptance activity and use that in the API call.

**Comment by jaapjansma** [comment]
My proposed fix wont work as I have traced back the issue to a bug in the activity api. It is visible in CiviCRM 4.6 and in the Dutch installation.

It is in the file api/v3/Activity.php line 247:

```php
$activityContactOptions = array(
      'target_contact_id' => array_search('Activity Targets', $options),
      'source_contact_id' => array_search('Activity Source', $options),
      'assignee_contact_id' => array_search('Activity Assignees', $options),
    );
```

Below the canhes to get this gdpr extension working:

```php
$activityContactOptions = array(
      'target_contact_id' => array_search(ts('Activity Targets'), $options),
      'source_contact_id' => array_search(ts('Activity Source'), $options),
      'assignee_contact_id' => array_search(ts('Activity Assignees'), $options),
    );
```

**Comment by sluc23** [comment]
@jaapjansma changing api/Activity with your suggestion and still getting same error.
Did you find a way to fix this (in our case CiviCRM 4.6.30 / Spanish)?

**Comment by jaapjansma** [comment]
@sluc23 I dont have a clue. Sounds like you did not fix it correctly... But that is hard to imagine.

**Comment by tbuytaer** [comment]
@sluc23 Did you clear the php cache files after you made the changes?
(The templates_c folder)
