### ISSUE TITLE
Can't uninstall or upgrade

### ISSUE THREAD

**Issue by mikantchap** [veda-consulting/uk.co.vedaconsulting.gdpr#96]
Trying to move from 2.3 to 2.5. 

We are getting this message when we try to uninstall 2.3 or try to upgrade to 2.5

[Error: Upgrade uk.co.vedaconsulting.gdpr to revision 1201]
API error: Value already exists in the database

Is there a way to manually uninstall the extension so that we can start again?

**Comment by mikantchap** [comment]
#0 /home/endometriosisuk/public_html/sites/all/modules/civicrm/CRM/Core/ManagedEntities.php(234): CRM_Core_ManagedEntities->onApiError("ReportTemplate", "create", (Array:5), (Array:3))
#1 /home/endometriosisuk/public_html/sites/all/modules/civicrm/CRM/Core/ManagedEntities.php(179): CRM_Core_ManagedEntities->insertNewEntity((Array:4))
#2 /home/endometriosisuk/public_html/sites/all/modules/civicrm/CRM/Core/ManagedEntities.php(141): CRM_Core_ManagedEntities->reconcileEnabledModule(Object(CRM_Core_Module), (Array:3))
#3 /home/endometriosisuk/public_html/sites/default/files/civicrm/extensions/uk.co.vedaconsulting.gdpr/CRM/Gdpr/Upgrader.php(146): CRM_Core_ManagedEntities->reconcileEnabledModules()
#4 [internal function](): CRM_Gdpr_Upgrader->upgrade_1201()
#5 /home/endometriosisuk/public_html/sites/default/files/civicrm/extensions/uk.co.vedaconsulting.gdpr/CRM/Gdpr/Upgrader/Base.php(72): call_user_func_array((Array:2), (Array:0))
#6 [internal function](): CRM_Gdpr_Upgrader_Base::_queueAdapter(Object(CRM_Queue_TaskContext), "upgrade_1201")
#7 /home/endometriosisuk/public_html/sites/all/modules/civicrm/CRM/Queue/Task.php(88): call_user_func_array((Array:2), (Array:2))
#8 /home/endometriosisuk/public_html/sites/all/modules/civicrm/CRM/Queue/Runner.php(214): CRM_Queue_Task->run(Object(CRM_Queue_TaskContext))
#9 /home/endometriosisuk/public_html/sites/all/modules/civicrm/CRM/Queue/Page/AJAX.php(52): CRM_Queue_Runner->runNext(TRUE)
#10 /home/endometriosisuk/public_html/sites/all/modules/civicrm/CRM/Queue/ErrorPolicy.php(106): CRM_Queue_Page_AJAX::{closure}()
#11 /home/endometriosisuk/public_html/sites/all/modules/civicrm/CRM/Queue/Page/AJAX.php(54): CRM_Queue_ErrorPolicy->call(Object(Closure))
#12 [internal function](): CRM_Queue_Page_AJAX::runNext()
#13 /home/endometriosisuk/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(275): call_user_func((Array:2))
#14 /home/endometriosisuk/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:13))
#15 /home/endometriosisuk/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:4))
#16 /home/endometriosisuk/public_html/sites/all/modules/civicrm/drupal/civicrm.module(445): CRM_Core_Invoke::invoke((Array:4))
#17 [internal function](): civicrm_invoke("queue", "ajax", "runNext")
#18 /home/endometriosisuk/public_html/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:3))
#19 /home/endometriosisuk/public_html/index.php(21): menu_execute_active_handler()
#20 {main}

**Comment by mikantchap** [comment]
$ManagedEntities_failed = Array ( [entity] => ReportTemplate [action] => create [params] => Array ( [version] => 3 [label] => Volunteer Report [class_name] => CRM_Volunteer_Form_VolunteerReport [description] => Volunteer Report [report_url] => volunteer ) [result] => Array ( [tip] => add debug=1 to your API call to have more info about the error [is_error] => 1 [error_message] => Value already exists in the database ) )

**Comment by mikantchap** [comment]
Managed to install 2.5 in the end by commenting out these lines:

  public function upgrade_1201() {
    $this->ctx->log->info('Applying update 1.2.0.1');
    //CRM_Core_ManagedEntities::singleton(TRUE)->reconcileEnabledModules();
    $this->executeCustomDataFile('xml/CustomGroupData.xml');
    return TRUE;
  }

  public function upgrade_1203() {
    $this->ctx->log->info('Applying update 1.2.0.3');
    // Reconcile managed entity for upgrade v2.0 -> v2.2.1
    //CRM_Core_ManagedEntities::singleton(TRUE)->reconcileEnabledModules();
    $this->executeCustomDataFile('xml/CustomGroupData.xml');
    return TRUE;
  }

These are adding a report template that already exists?
I'm not confident that we have installed 2.5 fully/correctly.

**Comment by veda-consulting** [comment]
@mikantchap we'll get someone to have a look and feedback.

**Comment by mikantchap** [comment]
Getting this error on a different site now when I try to run the db updates for ver 2.6:

[Error: Upgrade uk.co.vedaconsulting.gdpr to revision 1201]
Exception: "API error: DB Error: already exists"

#0 /home/togtrust/public_html/sites/all/modules/civicrm/CRM/Core/ManagedEntities.php(234): CRM_Core_ManagedEntities->onApiError("RelationshipType", "create", (Array:10), (Array:4))
#1 /home/togtrust/public_html/sites/all/modules/civicrm/CRM/Core/ManagedEntities.php(179): CRM_Core_ManagedEntities->insertNewEntity((Array:6))
#2 /home/togtrust/public_html/sites/all/modules/civicrm/CRM/Core/ManagedEntities.php(141): CRM_Core_ManagedEntities->reconcileEnabledModule(Object(CRM_Core_Module), (Array:3))
#3 /home/togtrust/public_html/sites/default/files/civicrm/extensions/uk.co.vedaconsulting.gdpr/CRM/Gdpr/Upgrader.php(146): CRM_Core_ManagedEntities->reconcileEnabledModules()
#4 [internal function](): CRM_Gdpr_Upgrader->upgrade_1201()
#5 /home/togtrust/public_html/sites/default/files/civicrm/extensions/uk.co.vedaconsulting.gdpr/CRM/Gdpr/Upgrader/Base.php(72): call_user_func_array((Array:2), (Array:0))
#6 [internal function](): CRM_Gdpr_Upgrader_Base::_queueAdapter(Object(CRM_Queue_TaskContext), "upgrade_1201")
#7 /home/togtrust/public_html/sites/all/modules/civicrm/CRM/Queue/Task.php(88): call_user_func_array((Array:2), (Array:2))
#8 /home/togtrust/public_html/sites/all/modules/civicrm/CRM/Queue/Runner.php(214): CRM_Queue_Task->run(Object(CRM_Queue_TaskContext))
#9 /home/togtrust/public_html/sites/all/modules/civicrm/CRM/Queue/Page/AJAX.php(52): CRM_Queue_Runner->runNext(TRUE)
#10 /home/togtrust/public_html/sites/all/modules/civicrm/CRM/Queue/ErrorPolicy.php(106): CRM_Queue_Page_AJAX::{closure}()
#11 /home/togtrust/public_html/sites/all/modules/civicrm/CRM/Queue/Page/AJAX.php(54): CRM_Queue_ErrorPolicy->call(Object(Closure))
#12 [internal function](): CRM_Queue_Page_AJAX::runNext()
#13 /home/togtrust/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(278): call_user_func((Array:2))
#14 /home/togtrust/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:13))
#15 /home/togtrust/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:4))
#16 /home/togtrust/public_html/sites/all/modules/civicrm/drupal/civicrm.module(482): CRM_Core_Invoke::invoke((Array:4))
#17 [internal function](): civicrm_invoke("queue", "ajax", "runNext")
#18 /home/togtrust/public_html/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:3))
#19 /home/togtrust/public_html/index.php(21): menu_execute_active_handler()
#20 {main}

**Comment by mikantchap** [comment]
And when I try to view a contact I get this also:

CiviCRM_API3_Exception: "'SLA Acceptance' is not a valid option for field activity_type_id"

#0 /home/togtrust/public_html/sites/default/files/civicrm/extensions/uk.co.vedaconsulting.gdpr/CRM/Gdpr/SLA/Utils.php(119): civicrm_api3("Activity", "get", (Array:4))
#1 /home/togtrust/public_html/sites/default/files/civicrm/extensions/uk.co.vedaconsulting.gdpr/gdpr.php(547): CRM_Gdpr_SLA_Utils::getContactLastAcceptance("17508")
#2 /home/togtrust/public_html/sites/all/modules/civicrm/CRM/Utils/Hook.php(201): gdpr_civicrm_pageRun(Object(CRM_Contact_Page_View_Summary))
#3 /home/togtrust/public_html/sites/all/modules/civicrm/CRM/Utils/Hook/DrupalBase.php(87): CRM_Utils_Hook->runHooks((Array:86), "civicrm_pageRun", 1, Object(CRM_Contact_Page_View_Summary), NULL, NULL, NULL, NULL, NULL)
#4 /home/togtrust/public_html/sites/all/modules/civicrm/CRM/Utils/Hook.php(736): CRM_Utils_Hook_DrupalBase->invoke(1, Object(CRM_Contact_Page_View_Summary), NULL, NULL, NULL, NULL, NULL, "civicrm_pageRun")
#5 /home/togtrust/public_html/sites/all/modules/civicrm/CRM/Core/Page.php(182): CRM_Utils_Hook::pageRun(Object(CRM_Contact_Page_View_Summary))
#6 /home/togtrust/public_html/sites/all/modules/civicrm/CRM/Contact/Page/View/Summary.php(103): CRM_Core_Page->run()
#7 /home/togtrust/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(312): CRM_Contact_Page_View_Summary->run((Array:3), NULL)
#8 /home/togtrust/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:14))
#9 /home/togtrust/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:3))
#10 /home/togtrust/public_html/sites/all/modules/civicrm/drupal/civicrm.module(482): CRM_Core_Invoke::invoke((Array:3))
#11 [internal function](): civicrm_invoke("contact", "view")
#12 /home/togtrust/public_html/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2))
#13 /home/togtrust/public_html/index.php(21): menu_execute_active_handler()
#14 {main}

**Comment by mikantchap** [comment]
Make sure you don't have error from other extensions!

https://github.com/veda-consulting/uk.co.vedaconsulting.gdpr/issues/134

**Comment by mikantchap** [comment]
https://github.com/veda-consulting/uk.co.vedaconsulting.gdpr/issues/134

**Comment by TerryVeda** [comment]
"SLA" error message for issues 96, 132, 154
