### ISSUE TITLE
Data Policy web page link instead of uploaded file

### ISSUE THREAD

**Issue by piyushkshah** [veda-consulting/uk.co.vedaconsulting.gdpr#97]
Thank you for this brilliant extension!

I think it would be useful to provide the option to choose an existing web page to link to for the data policy instead of having to upload a pdf file. 

This is true also for the terms and conditions. 

I guess it would also be necessary to have the option to indicate whether the policy page has changed - the 'This is a new version of the document.' versioning checkbox option.

**Comment by veda-consulting** [comment]
@piyushkshah thanks for the feedback.

Its a deliberate decision to not link to web pages as we need to keep a copy of the policy and share it to avoid large amounts of storage. If we provided a link we'd need to somehow capture the content every time someone accepted to ensure we have an exact copy of what they agreed to.

Unless theres a large consensus to have this option we wont be considering it I'm afraid.

**Comment by veda-consulting** [comment]
PR is merged, will be released with 4.7
