### ISSUE TITLE
Extrension not found for D7/Civicrm 5.1.0

### ISSUE THREAD

**Issue by Rar9** [veda-consulting/uk.co.vedaconsulting.gdpr#98]
Extension is not listed for D7/CiviCRM 5.1.0

/civicrm/admin/extensions

try to manually download version 2.5 and extract it to /site/default/files/civicrm/custom  but it still doesn't show.

**Comment by Upperholme** [comment]
It will only show if that directory is the one you have identifed in your configuration as the place where you want all your extensions to be. As in https://your.domain/civicrm/admin/setting/path?reset=1

**Comment by veda-consulting** [comment]
@Rar9 we do have it running in a number of CiviCRM 5.0 and 5.1 sites, not had the issues you've mentioned if everything is configured correctly. Don't forget to hit the refresh button the extensions listing to clear you extension cache.

**Comment by Rar9** [comment]
hmm.  I did another refresh today and no change.

Then I search for uk.co.vedaconsulting &  i see  only other modules like 
giftaidonline/ mailchimp / civicrmpostcodelookup /gotowebinar /mosaico but NO GDPR

So I checked the defined path under /civicrm/admin/setting/path?reset=1 for the manual uploaded module and moved it  from custom to ext .

Only then is see the GDPR  extension. :-)
